### ISSUE TITLE
UC发送的通知有些事XML格式，这时会被CI的核心input过滤掉 key

### ISSUE THREAD

**Issue by lixiaokai2008** [CodeIgniter-Chinese/ucenter-how-to#1]
因为通知时POST的XML格式如下：
$_post['<?xml version='] = '"1.0" encoding="utf-8"?> ....;'
这时的key不合符CI的要求，要被过滤掉

**Comment by chekun** [comment]
对的，确实有这个问题的，解决方法，就是扩展CI_Input排除这个就可以了。

**Comment by lixiaokai2008** [comment]
其实还有一个问题，我已经在HEX发布的帖子13楼做了解释，不知道是否解释得当
http://codeigniter.org.cn/forums/forum.php?mod=redirect&goto=findpost&ptid=17569&pid=79323&fromuid=6531

**Comment by chekun** [comment]
@lixiaokai2008 :+1: 可以fork本项目，然后pull request过来，感谢奉献。
